#theme: minima

remote_theme: jekyll/minima
minima:
  skin: dark

title: "jernwerber.dev: words, data & code"
author: "Jonathan Weber"

description: >
  Selected works of Jonathan Weber (@jernwerber), maker, tinkerer software 
  developer, educational researcher and instructional designer, specializing 
  in coding & science, technology, engineering, and mathematics (STEM) skills 
  development.

markdown: kramdown

url: "https://jernwerber.dev"

collections:
  portfolio:
    output: true

header_pages:
  - page-about.md
  - page-posts.html
  - page-portfolio.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

paginate: 5 

twitter_username: jernwerber
github_username: jernwerber
linkedin_username: jnthn-wbr

google_analytics: G-VVEDYZ776Q
show_excerpts: true

