theme: minima
title: "jernwerber.dev: words and code"
author: "jernwerber"
description: "Selected works of Jonthan Weber (@jernwerber) with some bonus words and code."
markdown: kramdown

twitter_username: jernwerber
github_username: jernwerber

google_analytics: G-VVEDYZ776Q
show_excerpts: true
excerpt_separator: <!--more-->
